name: Build and Release Go Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build Go program
        run: go build -o myprogram ./path/to/your/go/package

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(./myprogram -v)
          echo "::set-output name=version::$VERSION"

      - name: Create or Update Release
        id: create_or_update_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: myprogram
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            Release ${{ steps.get_version.outputs.version }}

          draft: false
          prerelease: false
