name: Construire et ajouter un programme Go à la release

on:
  release:
    types: [created]

jobs:
  build:
    name: Construire et ajouter le programme Go à la release
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2

      - name: Installer Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: Construire le programme Go
        run: go build -o CliImageDisplayer

      - name: Créer une nouvelle release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Description de la release
          draft: false
          prerelease: false

      - name: Téléverser le programme Go à la release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./CliImageDisplayer
          asset_name: CliImageDisplayer
          asset_content_type: application/octet-stream
