name: Create Release on Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5 # Remplacez par votre version de Go

      - name: Build Go program
        run: go build -o myprogram

      - name: Get program version
        id: version
        run: |
          program_version=$(./myprogram --version)
          echo "::set-output name=version::$program_version"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ steps.version.outputs.version }}
          body: |
            Release created automatically on commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CliImageDisplayer
          path: ./myprogram
